# Generated by Django 3.1.7 on 2021-03-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('img_url', models.URLField(max_length=600)),
                ('github', models.URLField(max_length=600)),
                ('live', models.URLField(max_length=600)),
                ('ruby', models.BooleanField()),
                ('python', models.BooleanField()),
                ('javascript', models.BooleanField()),
                ('react', models.BooleanField()),
                ('jquery', models.BooleanField()),
                ('express', models.BooleanField()),
                ('rails', models.BooleanField()),
                ('django', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'projects',
            },
        ),
    ]
